# -*- coding: utf-8 -*-

import datetime as dt
import os

timestart = dt.datetime(2018,1,5,0,0,0)


folder = os.path.dirname(os.path.abspath("__file__")) + "\\Raw_Data"
rawtext_csvfile_reddit = folder + "\\rawtext_reddit.csv"
rawtext_csvfile_twitter = folder + "\\rawtext_twitter.csv"

keywords = {
        'BTC': {
                'keywords' : ['bitcoin', 'bitcoins', 'xbt', 'btc', 'Bitcoin', 'Bitcoins', 'BTC', 'XBT']},
        'ETH': {
                'keywords' : ['ethereum', 'Ethereum', 'eth', 'ETH', 'ether', 'Ether']},
        'LTC': {
                'keywords' : ['litecoin', 'Litecoin', 'ltc', 'LTC']}
        }


subreddits = ["Agrello",
"altcoin",
"altcoin_news",
"ArkEcosystem",
"Best_of_Crypto",
"bitcoin",
"bitcoin_cash",
"Bitcoin_China",
"Bitcoin_Classic",
"bitcoin_uncensored",
"bitcoin_unlimited",
"BitcoinAll",
"bitcoinall",
"BitcoinBeginners",
"Bitcoincash",
"BitcoinMarkets",
"bitcoinxt",
"BlockChain",
"btc",
"btcforum",
"btcnews",
"BytecoinBCN",
"cloudmining",
"crypto_anarchism",
"crypto_currency",
"crypto101",
"CryptoCurrencies",
"cryptocurrency",
"CryptoCurrencyLive",
"CryptoMarkets",
"dash",
"decred",
"district0x",
"dnttrader",
"dogecoin",
"enigmacatalyst",
"EsotericInvestments",
"EthAnalysis",
"ethdev",
"ethereum",
"EthereumClassic",
"EthereumLand",
"ethereumnoobies",
"EtherMining",
"ethernews",
"ETHETC",
"ethfinex",
"ethinvestor",
"ethlaw",
"ethmarket",
"ethtrader",
"FuckToken",
"gpumining",
"iconomi",
"iconomiuncensored",
"Lisk",
"litecoin",
"litecoinforbeginners",
"LitecoinMarkets",
"litecoinmining",
"locallitecoins",
"MoneroCommunity",
"moneromarket",
"moneromarkets",
"MoneroMining",
"nem",
"NEO",
"NXT",
"nxtcoin",
"OMGTraders",
"omise_go",
"omisego",
"PnDCrypto",
"primecoin",
"Qtum",
"qtumtrader",
"reidao",
"ripplers",
"RippleTalk",
"santiment",
"scryptmining",
"siacoin",
"STOX",
"Stratis",
"TenX",
"tether",
"TREZOR",
"vergecurrency",
"worldcryptonetwork",
"xmrtrader",
"XRP",
"zcash_uncensored",
"zec"]